package server.enums;

public enum ActionType {
	AUTHENTICATION, ADMIN_ACTION, CHEF_ACTION, EMPLOYEE_ACTION, VIEW_MENU_ITEMS, ADD_MENU_ITEM, UPDATE_MENU_ITEM,
	DELETE_MENU_ITEM, GENERATE_RECOMMENDED_MENU, VIEW_RECOMMENDED_MENU, ADD_TO_ROLLOUT_MENU, VIEW_ROLLOUT_MENU,
	VIEW_FEEDBACK, VIEW_DISCARD_MENU_ITEMS, REMOVE_DISCARD_FOOD_ITEM, GET_DETAILED_FEEDBACK, VIEW_NOTIFICATIONS,
	VOTE_ROLLOUT_ITEMS, PROVIDE_FEEDBACK, UPDATE_PROFILE, DISCARD_MENU_FEEDBACK, VIEW_DISCARD_MENU_FEEDBACK,
	VIEW_DISCARD_MENU_NOTIFICATIONS;

	public static ActionType fromString(String action) {
		try {
			return ActionType.valueOf(action);
		} catch (IllegalArgumentException e) {
			return null;
		}
	}
}
